name: Minimal Check
on: [push, pull_request]

jobs:
  trivial:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run a trivial check
      run: echo "This is a minimal check"
